ecommerce/cart/urls.py
from . import views
from django.urls import path

app_name='cart'
urlpatterns=[
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>',views.add_cart,name='add_cart'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove')
]

ecommerce/searchapp/urls.py
from django.urls import path
from .import views

app_name='searchapp'

urlpatterns=[
    path('searchapp/',views.searchresult,name='searchresult')
]

ecommerce/shopapp/urls.py
from django.urls import path
from . import views

app_name = "shopapp"
urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetails,name='proCatDetails')
]

staticapp/urls.py
from .import views
from django.urls import path

urlpatterns = [
       path('',views.demo,name='demo')
]

staticproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from staticproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('staticapp.urls')),
    path('credentials/',include('credentials.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
             document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,
             document_root=settings.MEDIA_ROOT)

ecommerce/cart/models.py
from django.db import models
from shopapp.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)

class CartITem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self):
        return '{}'.format(self.product)

ecommerce/searchapp/models.py
from django.db import models

# Create your models here.

ecommerce/shopapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def get_urls(self):
        return reverse('shopapp:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)


    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'
    def __str__(self):
        return '{}'.format(self.name)
    def get_url(self):
        return reverse('shopapp:proCatDetails',args=[self.category.slug,self.slug])

ecommerce/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shopapp.models import Product
from .models import Cart,CartITem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=cart_id(request))
        cart.save()
    try:
        cart_item=CartITem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()
    except CartITem.DoesNotExist:
        cart_item=CartITem.objects.create(product=product,quantity=1,cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))
        cart_items=CartITem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total +=cart_item.product.price * cart_item.quantity
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartITem.objects.get(product=product,cart=cart)
    if(cart_item.quantity > 1):
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')
def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartITem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerce/searchapp/views.py
from django.shortcuts import render
from shopapp.models import Product
from django.db.models import Q
# Create your views here.

def searchresult(request):
     products=None
     query=None
     if 'q' in request.GET:
         query=request.GET.get('q')
         products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
         return render(request,'search.html',{'query':query,'products':products})

ecommerce/shopapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category,Product
from django.core.paginator import Paginator,InvalidPage,EmptyPage
# Create your views here.
def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug !=None:
         c_page=get_object_or_404(Category,slug=c_slug)
         products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
         products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page= 1
    try:
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request,"category.html",{'category':c_page,'products':products})
def proDetails(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

ecommerce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300&display=swap" rel="stylesheet">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
    {% include 'footer.html' %}
  <script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Please add items into your cart
{% endblock %}
{% block title %}
       Cart
{% endblock %}
{% block content %}
{% if not cart_items %}
   <div>
       <div class="text-center">
           <br>
           <h1 class="text-center my-title">Your shopping cart is empty</h1><br>
           <p class="text-center">Please click <a href="{% url 'shopapp:allProdCat' %}">Here</a> to add items</p>
       </div>
   </div>
{% else %}
<div>
    <div class="text-center"><br>
        <h1 class="text-center my-title">Your shopping cart</h1>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-mx-12 col-md-12 col-lg-6 text-center">
        <table class="table my-custom-table">
            <thead class="my-custom-thead">
            <tr>
                <th colspan="5">Your items</th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url">
                        <img src="{{cart_item.product.image.url}}" alt="image" style="height:100px;width:100;" class="float left rounded custom-image">
                    </a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}<br>
                    SKU:{{cart_item.product.id}}<br>
                    Price:{{cart_item.product.price}}<br>
                    Quantity:{{cart_item.quantity}} x {{cart_item}}

                </td>
                <td>
                    Rs.{{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom-a"> <i class="fa fa-plus"></i></a>&nbsp;
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom-icon"><i class="fa fa-minus"></i></a>&nbsp;
                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom-icon"><i class="fa fa-trash"></i></a>

                </td>
                {% else %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom-a"><i class="fa fa-plus"></i></a>&nbsp;
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom-icon"><i class="fa fa-minus"></i> </a>&nbsp;
                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom-icon"><i class="fa fa-trash"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my-custom-table">
            <thead class="my-custom-thead">
                 <tr><th>Checkout</th></tr>
            </thead>
            <tbody>
            <tr>
                <td>Please review your cart items before proceeding with payment</td>
            </tr>
            <tr>
                <td>
                <div class="mx-auto">
                  <a href="{% url 'shopapp:allProdCat' %}" class="btn btn-secondary btn-block my-custom-button">Continue shopping</a>
                </div>
                </td>
            </tr>
            <tr>
                <td>
                    <strong>Your cart total:{{ total }}</strong>
                </td>
            </tr>
              <tr>
                <td>
                <div class="mx-auto">
                  <a href="{% url 'shopapp:allProdCat' %}" class="btn btn-secondary btn-block my-custom-button">Make Payment</a>
                </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
{% endif %}
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {% if category %}
      {{category.description|truncatewords:155 }}
   {% else %}
      welcome to My shoppe, where you can buy different items
   {% endif %}
{% endblock %}
{% block title %}
{% if category %}
   {{category.name}}-My shoppe
{% else %}
   see our new collection
{% endif %}
{% endblock %}

{% block content %}
{% if category %}
  <div>
     <div class="row my-row-class">
        <div class="mx-auto">
            <p><a href="{% url 'shopapp:allProdCat' %}">Our product collection</a></p>

        </div>
     </div>
  </div>
{% endif %}
<div class="mx-auto">
   {% if category %}
     <img class="my-image" src="{{category.image.url}}" alt="{{category.name}}" height="150px" width="180px">
</div>
<br>
<div>
   <h1 class="text-center my-title">{{category.name}}</h1>
   <p class="text-justify">{{category.description}}</p>
</div>
   {% else %}
<div>
   <img class="my-image my-image-padding" src="{% static 'img/banner.png' %}" alt="our products" height="250px" width="1500px">
</div>
<br>
<div>
   <h1 class="text-center my-title">Our product collection</h1>
   <p class="text-justify">making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
   </p>
</div>
{% endif %}
<div class="container">
   <div class="row mx-auto">
      {% for product in products.object_list %}
      <div class="my-bottom-margin col-9 col-sm-12 col-md-4 xol-lg-4" >
         <div class="card text-center" style="min-width:18rem;">
            <a href="{{product.get_url}}"><img src="{{product.image.url}}" class="card-ing-top my-image" alt="{{product.name}}" height="150px" width="150px"></a>
            <div class="card-body">
               <h4>{{product.name}}</h4>
               <p>Rs.{{product.price}}</p>
            </div>
         </div>
      </div>
      {% endfor %}
   </div>
   <div class="mx-auto">
      {% if products.paginator.num_pages > 1 %}
      <hr>
      <div class="text-center">
         {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn dtn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
         {% endfor %}
      </div>
      {% endif %}
   </div>
</div>
{% endblock %}

ecommerce/templates/footer.html
<div class="footer navbar-fixed-bottom my-footer">
  <p class="text-center">@copy:My shoppe.All rights reserved</p>

</div>

ecommerce/templates/header.html
{% load static %}
<header>
    <center>
        <img src="{% static 'img/logo.png' %}" alt="logoimage" height="150px" width="100px">
    </center>
</header>

ecommerce/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
   <div class="container-fluid">
     <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shopapp:allProdCat' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'shopapp:allProdCat' %}">All product</a></li>
            {% for cat in links %}
               <li><a class="dropdown-item" href="{{cat.get_urls}}">{{cat.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
          {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart"></i>({{item_count}})</a>
        </li>
          {% endif %}
      </ul>
      <form class="d-flex" role="search" action="{% url 'searchapp:searchresult' %}" method="get">
          {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {{product.description |truncatewords:155}}
{% endblock %}
{% block title %}
  {% if category %}
     {{product.name}}
  {% endif %}
{% endblock %}
{% block content %}
<div class="my-prod-row-class">
   <div class="mx-auto">
      <p><a href="{% url 'shopapp:allProdCat' %}">home</a>|<a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}} </p>
   </div>
</div>
<div class="container">
<br>
<div class="row">
   <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
      <div style="min-width:18rem">
         <img src="{{product.image.url}}" alt="{{product.name}}">
      </div>
   </div>
   <div class="col-12 col-sm-12 col-md-12 col-lg-6">
      <div>
         <h1 class="my-prod-title">{{product.name}}</h1>
         <p>Rs.{{product.price}}</p>
         <p class="my-title"><b>product description</b></p>
         <p class="text-justify my-prod-text">{{product.description}}</p>
         {% if product.stock <= 0 %}
           <p class="text-justify my-prod-text"></p><b>Out of stock</b>
         {% else %}
            <a class="btn btn-secondary"  href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
         {% endif %}
      </div>
   </div>
</div>
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
     You can find item from our variety of collections
{% endblock %}
{% block title %}
     search
{% endblock %}
{% block content %}
<div class="text-center my-search-text">You are searched for:{{query}}

</div>
<div class="container">
 <div class="row mx-auto">
      {% for product in products %}
      <div class="my-bottom-margin col-12 col-sm-12 col-md-12 col-lg-6">
          <div class="card text-center" style="min-width:18rem;">
            <a href="{{product.get_url}}"><img src="{{product.image.url}}" class="card-ing-top my-image" alt="{{product.name}}" height="150px" width="150px"></a>
            <div class="card-body">
               <h4>{{product.name}}</h4>
               <p>Rs.{{product.price}}</p>
            </div>
         </div>
      </div>
      <div>
           {% empty %}
             <p class="text-center my-search-text">0 result found</p>
      </div>
      {% endfor %}
   </div>
</div>
{% endblock %}